name: 3dparadigm
favicon: null
layout_spectrum: 0.51454
typography_spectrum: 0.75047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8b6f5'
    - '#000000'
    - '#454d6f'
    - '#828ec3'
    - '#ecefff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.7422805652022362
  rhythmicContrast: 0.6742665257770568
purpose: []
